### ISSUE TITLE
it will be excellent to support several shortcodes 

### ISSUE THREAD

**Issue by emacsun** [kaushalmodi/ox-hugo#119]
ox-hugo is quite amazing. I use it almost everyday.

it will be excellent to support several shortcodes such as:

the alert shortcode:
{{% alert note %}}
Here's a tip or note...
{{% /alert %}}

the warning shortcode:
{{% alert warning %}}
Here's some important information...
{{% /alert %}}

and the effect can be found at https://sourcethemes.com/academic/docs/writing-markdown-latex/ 

I think it will be easy using the 
 #+begin_alert
 this is an alert
 #+end_alert

**Comment by kaushalmodi** [comment]
Hello!

Thanks for the kind words.

I looked at the theme [source][1], and the `alert` shortcode is simply:

```html
<div class="alert alert-{{ .Get 0 }}">
  {{ .Inner }}
</div>
```

I haven't yet tested, but to get the equivalent to:

```html
{{% alert note %}}
Here's a tip or note...
{{% /alert %}}
```

These ways should already work:

```org
#+begin_alert-note
Here's a tip or note...
#+end_alert-note
```

If you need to add `"alert"` class too, you can do instead:


```org
#+ATTR_HTML: :class alert
#+begin_alert-note
Here's a tip or note...
#+end_alert-note
```

Even this should work if your note is only one paragraph:

```org
#+ATTR_HTML: :class alert alert-note
Here's a tip or note...
```

---

Let me know if one or more of those ways work for you. These techniques should work for any shortcode that's simply a div wrapper with one or more classes, like this one. 

In the meanwhile, I'll think of an elegant way to export shortcodes in general. So I'll leave this issue open until then. 
[1]: https://github.com/gcushen/hugo-academic/blob/master/layouts/shortcodes/alert.html

**Comment by kaushalmodi** [comment]
@emacsun Tested that the above suggested ways already work.

[Org][1] → [Markdown][2] → [Hugo Output][3]

**Note**: I have a huge chunk of CSS on this test post because the test site does not use the Academic theme. As you are using the theme, you should need to only add this [extra CSS][4] to apply after your theme CSS is loaded.

*I will still keep this issue open till a proper way to export to Hugo shortcodes is figured out.*

[1]: https://github.com/kaushalmodi/ox-hugo/blame/cec4882d076f38d668fc1533cfa6292caf00a6b1/test/site/content-org/all-posts.org#L3007-L3156
[2]: https://raw.githubusercontent.com/kaushalmodi/ox-hugo/master/test/site/content/posts/alert-short-code-lookalike.md
[3]: https://ox-hugo.scripter.co/test/posts/alert-short-code-lookalike/
[4]: https://ox-hugo.scripter.co/test/posts/alert-short-code-lookalike/#css-override-for-academic-theme

**Comment by kaushalmodi** [comment]
Add support for exporting shortcodes:

- [ ] Those that do not needs arguments or parameters
- [ ] Those that **need** arguments or parameters

**Comment by kaushalmodi** [comment]
@emacsun Check out the commit message https://github.com/kaushalmodi/ox-hugo/commit/74cb3c2ec8c396bf8c305c339986d2b5c64bfb1b or the associated test case addition in that commit to see how you can now export shortcodes with positional arguments like the `alert` shortcode in your example.

That commit now resolves the feature you requested.. but I will wait for all my tasks I listed [here][1] to be completed before I close this ticket.

[1]: https://github.com/kaushalmodi/ox-hugo/issues/119#issuecomment-362343213

**Comment by emacsun** [comment]
@kaushalmodi thank you very much for your hard work! really appreciate it! It is perfect for me. Also you provide me more than one solution.

I will leave it for you to close this issue if you wish. :)

**Comment by kaushalmodi** [comment]
Glad to know that it's all good for you now. Just making sure that you follow the commit notes from https://github.com/kaushalmodi/ox-hugo/commit/0150797401693cee51fde03fa07a1f10d36915e9, and not from yesterday's commit. If you are using Melpa, the build from the referenced commit wouldn't be published by Melpa till about an hour or two. 

I'll close this issue once I've implemented passing of named args as well.
