### ISSUE TITLE
move the cross-reference function into markdown

### ISSUE THREAD

**Issue by emacsun** [kaushalmodi/ox-hugo#129]
Hi, Dear @kaushalmodi 

I know this is a complex problem, but it will be perfect for ox-hugo to support. As we all know, the Emacs Org support cross-reference between Org files. 

Furthermore, if you use the build-in publishing system of Emacs, the outputed .html can maintain the cross-reference. What about adding the cross-reference in ox-hugo?

About the cross-reference, I mean file, table, image cross-reference. 
for file it will be like [file:XXXX], for table it will be like [[table:tablename]] and image the same as table. for equation, it will be like \ref{eq:XXXX} to refer the \label{eq:XXXX}

thank you very much!

**Comment by kaushalmodi** [comment]
Hello,

You have listed a bunch of feature requests. Let me separate them out. 

- [ ] Cross-linking files. Is this to reference to other blog posts? If so, there is an issue open for that (https://github.com/kaushalmodi/ox-hugo/issues/30). Unfortunately, I don't know yet how to solve that problem. If it is not to link to other blog posts, can you please provide a minimum working example? 
- [x] Cross-linking tables. This is already working, as long as you are referencing to a table in the same file or post. Search for `tab__simple1` in the [test file][1] for an example of that. [Here's the HTML output][2] of that table linking test. **Note that a table needs to have a caption for the cross-linking to work.. all exporters have this requirement.**
- [x] Cross-linking figures. This is also already working, as long as you are referencing to a figure in the same file or post. Search for `img__org_logo1` in the [test file][1] for an example of that. [Here's the HTML output][3] of that figure/image linking test. **Note that a figure needs to have a caption for the cross-linking to work.. all exporters have this requirement.**
- [ ] Cross-linking of equations has yet to be implemented. 

---

- Please provide clarification and a test case for the file linking item above. 
- Also let me know if the table and image linking as shown in the linked examples works for you. *Note that Org does not recommend using `:` in the label names. If you do so, and run the Org linter, it will throw an error (Org 9.1.x - Stable version). So I am using `__` in label names instead of `:`.*

I'll open a separate issue for equation referencing. We can close this issue once the above questions are resolved. 

[1]: https://raw.githubusercontent.com/kaushalmodi/ox-hugo/master/test/site/content-org/all-posts.org
[2]: https://ox-hugo.scripter.co/test/posts/links-to-tables/
[3]: https://ox-hugo.scripter.co/test/posts/links-to-images/

**Comment by emacsun** [comment]
Hi @kaushalmodi 
Sure, you totally understand me. I really appreciate it! thank you. 

I check the cross-linking tables and figures, and it works. 

It surely takes time to finish the cross-linking file and equation. Never mind, I do cross-linking file by using the url address =https://= . 

For the cross-linking equaiton, I can name important equations while for the not so important equation, corss-linking is not necessary.

Thank you for your instant reply!

**Comment by kaushalmodi** [comment]
So looks like you want to cross link to other posts. You can do that easily with just `[[/posts/other-post][My other post]]` i.e. you don't even need the *https* portion. 

So, are you writing one post per file? Or do you export multiple posts from a single file, one post per subtree?

**Comment by kaushalmodi** [comment]
Hello, I'll close this issue, and have opened https://github.com/kaushalmodi/ox-hugo/issues/130 and https://github.com/kaushalmodi/ox-hugo/issues/131 (read details in there) instead.
