### ISSUE TITLE
Including mathjax?

### ISSUE THREAD

**Issue by amca01** [kaushalmodi/ox-hugo#151]
In the similar mode ox-reveal (for creating reveal.js presentations), mathjax can be included with the line

    #+REVEAL_MATHJAX_URL: https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-AMS-MML_HTMLorMML

I'm wondering if something similar is possible for ox-hugo?  Or is this a restriction from Hugo itself?  Currently I have to include the line 

    {{ partial "mathjax.html" . }}

in the `header.html` file of my theme, in its `layouts/partials` directory.  And I have a file `mathjax.html` in that same directory.  This seems clumsy; it'd be nice to be able to manage such inclusions from with the emacs file itself.  Anyway, thanks!

**Comment by kaushalmodi** [comment]
> In the similar mode ox-reveal (for creating reveal.js presentations), mathjax can be included with the line

>     #+REVEAL_MATHJAX_URL: https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-AMS-MML_HTMLorMML

That's possible in `ox-reveal`, etc. because those exporters generate complete HTML documents. `ox-hugo` generated just the content Markdown files. Hugo then converts that content to HTML and inserts that where you have `{{ .Content }}` in your Hugo templates.

So you cannot specify what scripts should be included in the HTML `<head>`.

> Currently I have to include the line
>     {{ partial "mathjax.html" . }}
> in the header.html file of my theme, in its layouts/partials directory.

That is the correct way! By rule of thumb, all repetitive code goes in your Hugo templates. Using `partial` like you do right now is NOT wrong!

>I'm wondering if something similar is possible for ox-hugo? 

It's possible, but it's not the canonical way. The scope of `ox-hugo` is just content, and does not leak into templating or code constructs that are common across pages. By "possible", I mean that `ox-hugo` can throw in a `<script> .. </script>` tag containing the mathjax script, but that wouldn't be the correct way. For instance, if you have a page listing a dozen blog posts in entirely, that script will be called a dozen times! So I will not implement that. As I said earlier, the correct way is adding that script tag in your HTML head or footer in Hugo layout files.

> Or is this a restriction from Hugo itself? 

No. It's just how layouts vs content work in Hugo. 

> And I have a file mathjax.html in that same directory. 

Can you elaborate on that? What's the "same directory" here? You must not have scripts, etc. in the Hugo content dir.

> This seems clumsy; 

May be things will be clearer once you elaborate more on above :)

> it'd be nice to be able to manage such inclusions from with the emacs file itself. Anyway, thanks!

This is out of the scope of `ox-hugo` as it exports only content files that get inserted where you have `{{ .Content }}` in your layouts. So putting scripts in content would be incorrect. But I'd be happy to help you resolve your confusion.

**Comment by kaushalmodi** [comment]
If you find your current file arrangement clumsy, I'd suggest using a more "modern" approach of templating.. using the `baseof.html` and `block`/`define` keywords. See [this][1] for more info.

I use that style in [`ox-hugo` test site][2] templates ([`hugo-bare-min-theme`][3]). 

- I define a `block` named `head` in that theme's `baseof.html` [here][4].
- Then `define` that `head` *block` in the theme's `single.html` [here][5] to include the `mathjax.html` partial.
- And finally that [partial][6].

[1]: https://gohugo.io/templates/base/#define-the-base-template
[2]: https://ox-hugo.scripter.co/test/posts/indented-equations/
[3]: https://github.com/kaushalmodi/hugo-bare-min-theme 
[4]: https://github.com/kaushalmodi/hugo-bare-min-theme/blob/a8eb82cfe5b2fedd21fac8e773c22e128ed7fe3e/layouts/_default/baseof.html#L82-L83
[5]: https://github.com/kaushalmodi/hugo-bare-min-theme/blob/a8eb82cfe5b2fedd21fac8e773c22e128ed7fe3e/layouts/_default/single.html#L1-L3
[6]: https://github.com/kaushalmodi/hugo-bare-min-theme/blob/a8eb82cfe5b2fedd21fac8e773c22e128ed7fe3e/layouts/partials/mathjax.html

**Comment by kaushalmodi** [comment]
I believe this can be closed here, and we can continue the discussion on Hugo Discourse.
