### ISSUE TITLE
Document how to use the slice-type `author` front-matter created by ox-hugo

### ISSUE THREAD

**Issue by elbaulp** [kaushalmodi/ox-hugo#178]
Hello, first of all thanks for developing this package. I am trying to migrate my blog to ox-hugo, but I am having some issues with how ox-hugo insert the `author` tag.

Currently in all  my post I have the author param as a single string, mixed in toml and yalm, because previously to hugo I was using jekyll:

```
author = "alex"
author: "alex"
```

Now, when I add this param in org I am doing:

```
#+author: alex
```

and it generates the param as an array:

```
author = ["alex"]
```

So, my theme I am retrieving the author as this:

```
{{ $au := or .Params.author "alex" }}
{{ $author := index .Site.Data.authors $au }}
```

but since now author can be a String or an `[]String` I am getting errors:

**error calling index: value has type []string; should be string**

I do not know what would be the best approach to handle this. Do I replace all params in all the post to convert them to array? or is there a way in hugo templating system to check a variable type? If there is, I could not find it in its documentation.

**Note**

I wanted to ask this in StackOverflow, but there isn't a `ox-hugo` tag. I could ask it there if it is more appropriate

**Comment by kaushalmodi** [comment]
Hello,

I create an `author` front-matter parameter because the traditional Org keyword is `#+author` as well (singular). Though, the same keyword can be stacked to allow multiple authors.

So the `author` front-matter is designed to always be a list. That way one or more authors can be supported.

Now, with the support in your Hugo template, you can update the template, or add this as a partial:

```html
{{ with .Params.author }}
    {{ $author_type := (printf "%T" .) }}
    {{ $author_is_slice := (eq "[]string" $author_type) }}
    <div class="author">
        {{ if $author_is_slice }}
            {{ index . 0 | safeHTML }}
        {{ else }}
            {{ . | safeHTML }}
        {{ end }}
    </div>
{{ end }}
```

*(not tested, but above or similar should work for your case.)*

What the above code does:

- If the `author` front-matter parameter exists:
  - If `author` is a slice (list), insert its first element,
  - Else, insert it whole.
 
If you are tweaking your own theme, just make it assume that the `.Params.author` is a slice.

Let me know if this works. If this doesn't work, a workaround is to manually set the `author` param as a string and not a slice.

```
#+hugo_custom_front_matter: :author "foo bar"
```

**Comment by elbaulp** [comment]
Thank you, this worked like a charm! I finally used this snipped:

```
{{ $au := or .Params.author "alex" }}
{{ $au_type := (printf "%T" $au) }}
{{ $au_is_slice := (eq "[]string" $au_type) }}
{{ if $au_is_slice }}
    {{ .Scratch.Set "__author_key" (index $au 0) }}
{{ else }}
    {{ .Scratch.Set "__author_key" $au }}
{{ end }}
{{ $author := index .Site.Data.authors (.Scratch.Get "__author_key") }}
```

You can see it working [in this commit](https://github.com/elbaulp/algui91-hugo/commit/0b2a8038ea215868be70c464abf2b27274f5b267), I referenced this issue to thank you.

I've seen you added the tag doc, could I help writing it?

**Comment by kaushalmodi** [comment]
> I've seen you added the tag doc, could I help writing it?

If you like to write it, you sure can. Thanks for offering your help :)

---

I would put this as a new section named "Author" in "Org to Hugo" section, after [Details and Summary][1]. 

See [Contribute to Documentation][2].

[1]: https://ox-hugo.scripter.co/doc/details-and-summary/
[2]: https://ox-hugo.scripter.co/doc/contributing-guide/#contribute-to-documentation

**Comment by kaushalmodi** [comment]
Fixed in https://github.com/kaushalmodi/ox-hugo/commit/f5ceeef456483033d22bee09cfad78083c122850 and https://github.com/kaushalmodi/ox-hugo/commit/e36e557cb8a0b5a1e2bbd3894d72ed417ee06435.
