### ISSUE TITLE
:PROPERTIES: seems to be ignored

### ISSUE THREAD

**Issue by mhatta** [kaushalmodi/ox-hugo#209]
Hi,

I installed ox-hugo and seems work mostly.  But in my environment, the markdown output of screenshot-subtree-export-example.org looks like:

```markdown
+++
author = ["Kaushal Modi"]
lastmod = 2018-09-20T13:57:24+09:00
draft = false
+++

## Emacs {#emacs}

All posts in here will have the category set to _emacs_.                       


### <span class="org-todo todo TODO">TODO</span> Writing Hugo blog in Org {#writ
ing-hugo-blog-in-org}


#### First heading within the post {#first-heading-within-the-post}            

-   This post will be exported as
    `content/posts/writing-hugo-blog-in-org-subtree-export.md`.                
-   Its title will be "Writing Hugo blog in Org".                       
(snip)
```
So somehow :PROPERTIES: is not parsed or ignored.  For other Org files, :PROPERTIES: works fine. I guess some lisp might not be loaded or missing...could you give me any hints?

I'm using Emacs 26.1 (or 25.2.2), Org 9.1.14, and using straight-el and use-package.  The other part of Org seems to work well.

**Comment by kaushalmodi** [comment]
For reference, [this][0] is the Org file. 

[Here][1] is the test suite generated Markdown file (I run the test suite in year 2100, arbitrarily picked, so that the lastmod date is the same in tests) , and [this][2] is the HTML output. 

Given that the file exports without any error, it looks like you have the package installed properly. 

I would suggest commenting out any Org related setup. 

My guess would be that something in your config, and one of the installed packages is overriding tbr the default property parsing behavior. 

So let's start with that debug step. Comment out all Org mode config, including Org related packages (except ox-hugo), restart Emacs and see if the export starts parsing the subtree properties. 

Also, how are you exporting? Did you do C-c C-e H H, with the point somewhere in the post subtree? You can also do C-c C-e H A to export all post subtrees in a file (just 1 in this case) without worrying about where the point is. 

[0]: https://raw.githubusercontent.com/kaushalmodi/ox-hugo/master/test/site/content-org/screenshot-subtree-export-example.org
[1]: https://raw.githubusercontent.com/kaushalmodi/ox-hugo/master/test/site/content/writing-hugo-blog-in-org-subtree-export.md
[2]: https://ox-hugo.scripter.co/test/writing-hugo-blog-in-org-subtree-export/

**Comment by mhatta** [comment]
Ah, my bad, seems my laptop's shift key doesn't work well, and somehow I unintentionally hit `C-e C-h H h`, instead of `H`.

Sorry about bothering you...close this now.

**Comment by kaushalmodi** [comment]
Ah yes, `C-c C-e H h` will export the whole Org file using *per-file* flow. So that treats the Org headings as post headings.

> Sorry about bothering you...close this now.

No problem

**Comment by flowsta** [comment]
Dear @kaushalmodi I think I have the same behaviour with my all-post.org file. I copy from one section to other the properties and it seems like if Org-mode/ox-hugo/wtf needs the property added through `C-c C-x p`

Does anyone else have experimented the same? Suggestions?

Best!

**Comment by kaushalmodi** [comment]
@flowsta The originator of this issue had this problem because of wrong key binding. 

Can you please open a new issue with a sample Org file and the actual and expected Markdown files on doing the export?
