### ISSUE TITLE
Translate Org CUSTOM_ID to Hugo heading anchor

### ISSUE THREAD

**Issue by kaushalmodi** [kaushalmodi/ox-hugo#22]
https://gohugo.io/extras/crossreferences/

> Specifying Heading Anchors

> You can also tell Hugo to use a particular heading anchor.

> `# Hugo: A Fast & Modern Static Web Engine {#hugo-main}`
>Hugo will use hugo-main as the heading anchor.

**Comment by kaushalmodi** [comment]
A bigger problem needs to be solved.. need to figure out how to access property drawer values when doing only single subtree export.

**Comment by titaniumbones** [comment]
This is kind d of a flaw in the org exporter system.  It seems obvious the headline title should take precedence over the do hment title, but it doesn't. 

I think org2blog has the expected behaviour, maybe we can look at their code. 

On July 1, 2017 2:48:22 AM EDT, Kaushal Modi <notifications@github.com> wrote:
>A bigger problem needs to be solved.. need to figure out how to access
>property drawer values when doing only single subtree export.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/kaushalmodi/ox-hugo/issues/22#issuecomment-312415018

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by kaushalmodi** [comment]
Discussion on Org mode mailing list: http://lists.gnu.org/archive/html/emacs-orgmode/2017-07/msg00000.html

**Comment by kaushalmodi** [comment]
CUSTOM_ID now translates to Hugo style heading anchor. See the [example-site][1].

[1]: https://raw.githubusercontent.com/kaushalmodi/ox-hugo/master/example-site/content-org/all-posts.org
