### ISSUE TITLE
Support maps of maps in front matter (theme Academic)

### ISSUE THREAD

**Issue by andreas-h** [kaushalmodi/ox-hugo#226]
I'm using the [Academic Theme](https://github.com/gcushen/hugo-academic).  They have a way of combing the homepage from several `.md` files, one could look [like this](https://raw.githubusercontent.com/gcushen/hugo-academic/master/exampleSite/content/home/about.md), e.g.:

    +++
    # About/Biography widget.
    widget = "about"
    active = true
    date = 2016-04-20T00:00:00
    
    # Order that this section will appear in.
    weight = 5
    
    # List your academic interests.
    [interests]
      interests = [
        "Artificial Intelligence",
        "Computational Linguistics",
        "Information Retrieval"
      ]
    
    # List your qualifications (such as academic degrees).
    [[education.courses]]
      course = "PhD in Artificial Intelligence"
      institution = "Stanford University"
      year = 2012
    
    [[education.courses]]
      course = "MEng in Artificial Intelligence"
      institution = "Massachusetts Institute of Technology"
      year = 2009
    
    [[education.courses]]
      course = "BSc in Artificial Intelligence"
      institution = "Massachusetts Institute of Technology"
      year = 2008
     
    +++
    
    # Biography
    
    Lena Smith is a professor of artificial intelligence at the Stanford AI Lab. Her research interests include distributed robotics, mobile computing and programmable matter. She leads the Robotic Neurobiology group, which develops self-reconfiguring robots, systems of self-organizing robots, and mobile sensor networks.
    
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed neque elit, tristique placerat feugiat ac, facilisis vitae arcu. Proin eget egestas augue. Praesent ut sem nec arcu pellentesque aliquet. Duis dapibus diam vel metus tempus vulputate. 

How can I get *ox-hugo* to create these lists (like `[interests = ...]` and `[[education.courses]] ...`) which both span over several lines, in the front matter of the exported Markdown?

**Comment by kaushalmodi** [comment]
So the day has finally come. Someone actually needs this feature? :P

This is a known limitation. See https://ox-hugo.scripter.co/doc/custom-front-matter/#maps-of-single-and-list-values: "Maps of maps are not supported.".

I didn't implement that because I wasn't sure if all the effort needed in designing this complicated feature would be worth it. 

But now I'll think of a user-friendly way of entering this table meta data in Org that would translate to that TOML table. 

I will work on this, but this feature is not a high priority.

**Comment by kaushalmodi** [comment]
> How can I get ox-hugo to create these lists (like [interests = ...] and [[education.courses]] ...) which both span over several lines, in the front matter of the exported Markdown?

Just to be clear, if you look at that link I pasted, the "interests" front-matter setting is already supported. 

But the "education.courses", which is a TOML table of tables, is not yet.

**Comment by kaushalmodi** [comment]
@andreas-h Hello, I thought a bit more about this. While I won't have time implementing a full-fledged parsing of *maps of maps* type front-matter, I have added a brute-force solution that would work for any kind of front-matter in https://github.com/kaushalmodi/ox-hugo/commit/ca0e602f7ede31313e028223965bd8aca99252c6.

See https://ox-hugo.scripter.co/doc/custom-front-matter/#front-matter-extra for details.

**Comment by andreas-h** [comment]
Hey, @kaushalmodi , that's so great - thanks a lot!  This actually solves all my needs :-)

**Comment by kaushalmodi** [comment]
I'll close this issue because, I haven't felt a real need to implement this feature in these many years (and it would be very complicated if I attempted to do it). 

Also [front matter extra](https://ox-hugo.scripter.co/doc/custom-front-matter/#front-matter-extra) already solves the need. 

So I'll close this issue. 

Thanks!
