### ISSUE TITLE
Inserting backslash at beginning of C++ includes in highlight shortcode

### ISSUE THREAD

**Issue by dm19** [kaushalmodi/ox-hugo#228]
Exporting

```
{{< highlight cpp >}}
#include <iostream>
#include <stdio>
{{< /highlight >}}
```
results in
```
\#include <iostream>
\#include <stdio>
```
Trying 

```
{{< highlight cpp >}}
=#= include <iostream>
=#= include <stdio>
{{< /highlight >}}
```
results in
```
`#` include <iostream>
`#` include <stdio>
```

**Comment by kaushalmodi** [comment]
Org doesn't understand the Hugo shortcode syntax.

You need to write the code block in Org syntax. How does the below export? 

```org
#+begin_src cpp
,#include <iostream>
,#include <stdio>
#+end_src
```

**Comment by kaushalmodi** [comment]
I am not at comp, so I haven't tried the above, may be you don't even need those comma escapes on the 2 lines.

**Comment by dm19** [comment]
That worked. Just had to set pygmentsCodefences = true in my config file instead of using the shortcode (and the commas are not needed). Thank you!

**Comment by kaushalmodi** [comment]
ox-hugo can always export to the `highlight` shortcode syntax in Markdown if you set `#+hugo_code_fence: nil` at the top of your Org file.

But I have set the default value of that config to `t` so that the standard triple-backtick code blocks are generated, because:

- It's a more concise syntax
- I have seen a Hugo bug that has to do with using `highlight` shortcode code blocks in lists (https://github.com/kaushalmodi/ox-hugo/issues/161).

See this doc page for complete details on Org Source block support in ox-hugo: https://ox-hugo.scripter.co/doc/source-blocks/.
