### ISSUE TITLE
support for "non-Hugo" markdown flavours

### ISSUE THREAD

**Issue by gour** [kaushalmodi/ox-hugo#260]
Hello,

for whatever reason, I have decided to use Nikola (instead of Hugo) and wonder if it would be possible to make ox-hugo usable for other static-site-generators (eg. Nikola, Pelican, etc.) by exporting python-extended markdown, Pandoc's extended markdown etc. or Hugo/Blackfriday's support is too hard-coded?

**Comment by kaushalmodi** [comment]
Hello,

>  if it would be possible to make ox-hugo usable for other static-site-generators (eg. Nikola, Pelican, etc.) by exporting python-extended markdown, Pandoc's extended markdown etc. or 

I do not use those static site generators. So I wouldn't be the right person to write an Org exporter for those, mainly because I would not have time to learn the requirements of those SSGs, and even if I did that, I wouldn't have time to keep the package updated with the development of those SSGs (which I actually do in the case of Hugo).

> Hugo/Blackfriday's support is too hard-coded?

Well, this package is designed just for Hugo. So I wouldn't call it "hard-coded" .. it addresses the front-matter parameters specific to Hugo in `ox-hugo`, and it fixes the Blackfriday Markdown parser specific quick in the `ox-blackfriday` package (that `ox-hugo` uses). So these are designed specifically for those.

---

That said, it should be relatively easy to tweak `ox-hugo` and `ox-blackfriday` to transform them into Org exporter backends for any other Markdown based SSGs. Give it a try and I would be happy to help you out.

**Comment by gour** [comment]
> I do not use those static site generators. So I wouldn't be the right person to write an Org exporter for those, mainly because I would not have time to learn the requirements of those SSGs, and even if I did that, I wouldn't have time to keep the package updated with the development of those SSGs (which I actually do in the case of Hugo).

That's clear. ;)

> Well, this package is designed just for Hugo. So I wouldn't call it "hard-coded" .. it addresses the front-matter parameters specific to Hugo in `ox-hugo`, and it fixes the Blackfriday Markdown parser specific quick in the `ox-blackfriday` package (that `ox-hugo` uses). So these are designed specifically for those.

Nikola can actually use Hugo's front-matter and can have TOML/YAML meta data, but then, when I'm thinking more deeply about it, you put a lot of effort into ox-hugo, having quite complete support of e.g. images which are e.g. broken in Nikola's orgmode plugin, maybe it's better to simply use ox-hugo :-)

Moreover, I see that you've created [component](https://github.com/kaushalmodi/hugo-search-fuse-js) to solve Search feature which bugged me in Hugo for a while - 3rd party services like Algolia are too expensive or one has to fiddle with JS, so it looks as switching back to (ox-)hugo is the optimal solution. ;)

**Comment by kaushalmodi** [comment]
Well, I believe that this issue is safe to be closed :). 

Feel free to comment further in this thread even after it getting closed.
