### ISSUE TITLE
Export source code blocks without language definition

### ISSUE THREAD

**Issue by iris-garcia** [kaushalmodi/ox-hugo#282]
## Actual Behavior
If the #+begin_src does not specify any language the exported markdown is:

\`\`\`nil
\`\`\`
## Expected Behavior
The exported markdown should be
\`\`\`
\`\`\`
## How to Reproduce the Issue
There is a problem in Hugo which does not format properly source blocks in a list, example:
```
1. Code one
    #+begin_src shell
       ls /
    #+end_src
2. Code two
    #+begin_src shell
       ls /tmp
    #+end_src
```

Is exported as:

1. Code one
\`\`\`shell
ls /
\`\`\`
2. Code two
\`\`\`shell
ls /tmp
\`\`\`

Which breaks the format in hugo.

A workaround in hugo is to just remove the language or set the indentation to 8 spaces.

None of them are possible using ox-hugo from an Org file.

**Comment by kaushalmodi** [comment]
Hello,

> If the #+begin_src does not specify any language  ..

I believe that's invalid Org mode syntax. But before I need to allow src blocks without a language, let's see if we can make the code blocks in lists work for you (because I have a small test where it worked: https://ox-hugo.scripter.co/test/posts/list-has-src-block-but-no-list-syntax/). 

Also, what is your Hugo version? I believe that last or second-last patch version of Hugo 0.55.x had an issue with src blocks in lists. Can you update Hugo to the the latest 0.56.0 and see if the issue is still there? 

> Which breaks the format in hugo.

Let's work on resolving this.

**Comment by iris-garcia** [comment]
Hi @kaushalmodi, thanks for your quick answer.

My hugo version is: v0.55.6

I'll update to the latest version and report back.

**Comment by iris-garcia** [comment]
Closing this issue, with the latest version of hugo everything works as expected, I should have check the version first, sorry for that :(.

**Comment by kaushalmodi** [comment]
Glad worries, glad it got resolved.
