### ISSUE TITLE
Investigate and remove the "_" to "%5f" hack added for Blackfriday.. may be that's not needed with Goldmark

### ISSUE THREAD

**Issue by kaushalmodi** [kaushalmodi/ox-hugo#308]

**Comment by luketurner** [comment]
I encountered issues with the %5F a while back -- It was breaking links, specifically, Github links. I believe that whether it breaks or not is dependent on how the server is parsing their path segments, so it's probably site-dependent.

e.g.:

- https://github.com/luketurner/qmk_firmware
- https://github.com/luketurner/qmk%5ffirmware

At least on my computer (tm) the first link works, the second returns a Page not found.

Anyway, I guessed it was due to Hugo's switch to Goldmark (I'm currently using Hugo `v0.81.0`) and have been running without the `org-blackfriday--url-sanitize` call for a while.
