### ISSUE TITLE
Better handling of images in Hugo bundles

### ISSUE THREAD

**Issue by kaushalmodi** [kaushalmodi/ox-hugo#324]
> @gour I had let this issue stay open as I wanted to document this feature for other users too. Now I have :)
> 
> The documentation is added at https://ox-hugo.scripter.co/doc/images-in-content/.
> 
> Feel free to reopen this issue or open a new one if you face any problem.

That's fine, but there is a major issue with saving images on `static` folder: those images cannot be processed by Hugo (see [Hugo Image processing](https://gohugo.io/content-management/image-processing) ).

I started my ox hugo experimentation with the strategy proposed by the hugo documentation ( [ox hugo Images in content](https://ox-hugo.scripter.co/doc/images-in-content/) ) but, having to process the images, at the moment I have to copy the files by hand to the directory containing the post. I am using `:EXPORT_HUGO_BUNDLE:` in order to create page bundles and I've disabled Emacs option `org-hugo-default-static-subdirectory-for-externals`.

It would be awesome that the images would be copied from the org directory to the page bundle directory.

_Originally posted by @finex in https://github.com/kaushalmodi/ox-hugo/issues/91#issuecomment-579876245_

**Comment by kaushalmodi** [comment]
@finex Can you please provide a minimal reproducible example of what's happening and what's the expectation?

**Comment by finex** [comment]
Hi, of course @kaushalmodi :-) 

# :no_good_man: Current behaviour:
_valid with bot single org file and one post per file_

ox-hugo copies images (from the post body) to /static folder (`org-hugo-default-static-subdirectory-for-externals`).

# :smile: Expected behaviour:

It should be added a new parameter to force the copy of images to the page bundle directory instead than the static one.

**Org file structure:**
```
content-org/posts.org 
content-org/image1.jpg
```

**posts.org details:**
It contains a reference to file:image1.jpg and has the `:EXPORT_HUGO_BUNDLE:` option set to `bundle-name` (it's an example). I've also set the hugo section to `blog` using `#+hugo_section: blog`.

**Result:**
When you save the .org file and export to hugo the directory with markdown (`content`) should be something like:
```
content/blog/bundle-name/index.md
content/blog/bundle-name/image1.jpg
```

# :heart: Extra "like to have" :
This option should be used also to enhance my previous report (#301 ): images on custom front matter should also be copied in the page bundle directory.

**Comment by finex** [comment]
Hi @kaushalmodi , did you evaluated my proposal? This is the last problem left which prevents me to use ox-hugo (and Hugo) for my new "ready to be launched" website 😀. Let me know if you've some suggestions, even a custom local script to automate this task. Thank you for all your work on this project!

**Comment by kaushalmodi** [comment]
Oh boy, it's already been 3 months since this issue was created.  My work's been too busy. I'll get to this once I find some time. Such major features need a lot of testing and also documentation.

**Comment by finex** [comment]
Great, I don't know elisp (yet) so I can't help with coding but if you need help for testing or something else feel free to ask :-) thank you! :-)

**Comment by kaushalmodi** [comment]
@finex I have already added this feature, but I misunderstood this feature request for something else :).

Well, now I have this documented as well. Please refer to this documentation on https://ox-hugo.scripter.co/doc/images-in-content/#images-and-page-bundles and let me know if that resolved this issue.

**Comment by finex** [comment]
Hi, yes, it works :-) Thank you :-)
