### ISSUE TITLE
Tag Hierarchy as defined in #+TAGS

### ISSUE THREAD

**Issue by tabroughton** [kaushalmodi/ox-hugo#341]
I wondered if it would be possible to export tags with hierarchy defined in the org-mode #TAGS

https://orgmode.org/manual/Tag-Hierarchy.html

**Comment by kaushalmodi** [comment]
We will need to define a little spec on how we want that to behave when exporting to Hugo tags.

Let's take the example from the manual:

---

You can set group tags by using brackets and inserting a colon between the group tag and its related tags—beware that all whitespaces are mandatory so that Org can parse this line correctly:

```
#+TAGS: [ GTD : Control Persp ]
```

In this example, ‘GTD’ is the group tag and it is related to two other tags: ‘Control’, ‘Persp’. Defining ‘Control’ and ‘Persp’ as group tags creates a hierarchy of tags:

```
#+TAGS: [ Control : Context Task ]
#+TAGS: [ Persp : Vision Goal AOF Project ]
```

That can conceptually be seen as a hierarchy of tags:

```
    ‘GTD’
        ‘Persp’
            ‘Vision’
            ‘Goal’
            ‘AOF’
            ‘Project’ 
        ‘Control’
            ‘Context’
            ‘Task’ 
```

---

Given above, if a post is tagged "Vision", should its `tags` front-matter look like below? :

```
tags = ["GTD", "Persp", "Vision"]
```

As an aside, have you tried out tags inheritance in sub-tree based exports?

![image](https://user-images.githubusercontent.com/3578197/78458867-a38d6480-7682-11ea-88fb-e8735889a59d.png)


---

_PS: I am currently bogged down with work stuff, but we can atleast start defining the spec in parallel._

**Comment by tabroughton** [comment]
> Given above, if a post is tagged "Vision", should its `tags` front-matter look like below? :

I like your approach using the org-mode examples.  Yes I agree that the front matter tags should look as you have specified given the structure and then tagging a something with `:Vision:`

This would be an excellent feature because I want to use various tags from different inheritance trees as it were for example, using the example you have laid out I might want to tag with both `:Vision:` and `:Task:` which should result in the following front matter:

```
tags = ["GTD", "Persp", "Vision", "Control", "Task"]
```

I can't do this with sub-tree inheritance even though in my personal approach I do use sub-tree based exports.

**Comment by tabroughton** [comment]
I imagine the spec would maintain the ox-hugo use of `_` (underscore) and `__` (double underscore) within tag text of the defined #+TAGS resulting in either a hyphen `-` or a space respectively.

**Comment by tabroughton** [comment]
It could also be possible to mix tags and categories within the definition.  So if we changed one of the examples to include the `@` sign 
```
#+TAGS: [ @Persp : Vision Goal AOF Project ]
```
And then tag with `:Vision:` again, the exported front matter would now be something like:
```
tags = ["GTD", "Vision"]
categories = ["Persp"]
```
This is how org-mode can be configured and I think it would be quite a powerful feature

**Comment by tabroughton** [comment]
> PS: I am currently bogged down with work stuff, but we can atleast start defining the spec in parallel.

Is there anything I can do to help spec this further?

**Comment by kaushalmodi** [comment]
Hi Tom, no, I have enough data to start implementing this feature. I just need time to implement this.

**Comment by kaushalmodi** [comment]
@tabroughton This is now implemented in https://github.com/kaushalmodi/ox-hugo/pull/506. It might not be the best algorithm to do the reverse search from each tag to the tag group's head, but it works 😄 .
