### ISSUE TITLE
"Table", "Caption", etc. strings are not translated to Romanian

### ISSUE THREAD

**Issue by ctanas** [kaushalmodi/ox-hugo#352]
Specifying a caption for images and tables within Emacs by using "#+CAPTION:" renders "Figure X ...", respectively "Table X ..." in the final markdown file, at the beginning of the caption. That's a nice feature, however, I have no control on the "Figure" and "Table" strings and for a generated site that's not in English, this is an issue. I would like to either suppress those strings, or, a more preferable approach, to alter them in my native language. Is there a way I could do this from within Emacs? Because manually editing every markdown file after each export isn't a solution.

**Comment by kaushalmodi** [comment]
The "Table" , "Caption", etc translation is done by automatically when you have a language keyword at the top of your Org file. 

I have a test case for `#+language: de`. [Here][1], you can see the "Table" and "Listing" get translated to German. The translation database is provided by Org (ox.el, I believe). 

Let me know if this works for your language. 

Ref: https://github.com/kaushalmodi/ox-hugo/issues/233#issuecomment-436441208

[1]: https://ox-hugo.scripter.co/test/singles/links-to-org-elements/

**Comment by ctanas** [comment]
I see. It does work for German, I just tried, but it doesn't work for my language, Romanian, since it's missing from ox.el. I can try and add Romanian support for ox.el.

**Comment by ctanas** [comment]
Apparently I can't just create a pull request for my patch. Could some programmer or anyone more skilled than me push this to upstream? I think I'd need an account at https://code.orgmode.org, that I don't have. Here's my modifications to include Romanian in ox.el:
https://github.com/ctanas/org/blob/cc9f255ea388bcf6d37583a689acd14e6831ee4d/lisp/ox.el

**Comment by kaushalmodi** [comment]
@ctanas Can you send that to the Org mailing list. That will be a very useful contribution.

Org mailing list: emacs-orgmode@gnu.org

If I add ".patch" to your commit that adds these translations, I see https://github.com/ctanas/org/commit/cc9f255ea388bcf6d37583a689acd14e6831ee4d.patch . You would copy/paste that and send that to the mailing list requesting that that be committed to the **maint** branch.

Before you do that, update the commit message so that it follows the Org commit message convention. See this earlier commit to ox.el that adds Italian translations: https://code.orgmode.org/bzg/org-mode/commit/638f329838ad1f981522a2813f3ada742de4077d

Hope that helps. 

_Congrats to your upcoming first (is that right?) contribution to Org mode!_ 🎉

**Comment by kaushalmodi** [comment]
In the meanwhile (while that commit gets into the maint branch and released into the next Org stable version the following Monday), a hack like this in your emacs config might work:

```el
(with-eval-after-load 'ox
  (setcdr (assoc "Caption" org-export-dictionary) 
          (append (cdr (assoc "Caption" org-export-dictionary)) 
                  '(("ro" :default "legendă"))))

  (setcdr (assoc "Table" org-export-dictionary) 
          (append (cdr (assoc "Table" org-export-dictionary)) 
                  '(("ro" :default "Tabel"))))
  )
```

**Comment by ctanas** [comment]
Great! Thank you!

**Comment by kaushalmodi** [comment]
I am looking forward to you sending your patch to the Org mailing list.

I believe we can close this issue then.
