### ISSUE TITLE
Don't escape underscores in citation keys

### ISSUE THREAD

**Issue by cpbotha** [kaushalmodi/ox-hugo#354]
## Actual Behavior

`What about [@chung_under2018] and [@jia2018]` in orgmode is converted to `What about [@chung\_under2018] and [@jia2018]` in the first stage markdown (note the `\_`), before being passed to pandoc.

pandoc then turns it into `What about (<span class="citeproc-not-found" data-reference-id="chung">**???**</span>\_under2018) and (Jia et al. 2018)`

As you can see, the `\_` understandably breaks the pandoc lookup for that citation key.

## Expected Behavior

Underscores in citation keys should not be escaped.

## How to Reproduce the Issue

Select any citation key and insert an underscore anywhere. Build the hugo page and see the citation stop working.

**Comment by kaushalmodi** [comment]
Hello,

Thanks for reporting this issue. This is because the escaping of `_` and other Markdown characters has been very over-eager (which I ported to `ox-blackfriday.el` too).

Hugo v0.60.0, the detection of `_`, etc. markup characters is a lot more sane as it switch to the Goldmark (Commonmark) library since then.

I am planning to spin-off an `ox-commonmark.el` from `ox-blackfriday.el` that undoes all the hacks that Blackfriday needed, but Commonmark does not.

That will also fix this issue indirectly. I will make sure I have a test in which has the citation keys with underscores.

Given that you would be using a Hugo version newer than 0.60.0, this issue will then get fixed for you.

**Comment by cpbotha** [comment]
Thank you very much @kaushalmodi !

For now I have installed the BetterBibtex extension in zotero, with which it's possible to configure exported bibtex keys without underscores.

**Comment by kaushalmodi** [comment]
@cpbotha It took a while, but it's finally fixed.
