### ISSUE TITLE
export menu alignment broken

### ISSUE THREAD

**Issue by andreyorst** [kaushalmodi/ox-hugo#357]
![image](https://user-images.githubusercontent.com/19470159/80785844-566db700-8b8a-11ea-8481-008c246de86a.png)

Also happens in `emacs -q`:

![image](https://user-images.githubusercontent.com/19470159/80785893-8917af80-8b8a-11ea-8fab-b818ec79781d.png)

**Comment by kaushalmodi** [comment]
Hmm, looks like I cannot have those key binding descriptions too long. I'll fix this. Thanks.

**Comment by kaushalmodi** [comment]
Now we will see something like this:

![image](https://user-images.githubusercontent.com/3578197/80808041-a77eaa80-8b8c-11ea-859c-fa3b18bff077.png)

Note that I chose not to align the second column with the rest of the export options because trying to do so was forcing me to make the descriptions too cryptic.
