### ISSUE TITLE
ox-hugo creates a new files when the file names are changed in org file.

### ISSUE THREAD

**Issue by mrprofessor** [kaushalmodi/ox-hugo#367]
## Ox-Hugo Debug Information

<details>
  <summary>Debug Info</summary>

  

</details>

**Comment by kaushalmodi** [comment]
Hello,

This behavior is by design. Ox-hugo works in a conservative fashion and doesn't delete any file, just in case a user has Hugo content dir with a mix of manually created and ox-hugo exported Markdown files. 

I can suggest that you rm -rf the entire content directory if you happen to rename a lot of exported files. Then export the whole Org file using C-c C-e H A.

**Comment by mrprofessor** [comment]
Since that you are here..

How can I store files in multiple directories?

```
posts/
    01.md
    02.md
logs/
    01.md
    02.md
about.md
```

**Comment by kaushalmodi** [comment]
> How can I store files in multiple directories?

See HUGO_SECTION.
