### ISSUE TITLE
[Suggestion] Generate Org file instead of Markdown file?

### ISSUE THREAD

**Issue by whhone** [kaushalmodi/ox-hugo#392]
ox-hugo exports Org to Markdown via Blackfriday. However, Hugo does support Emacs Org-Mode formats ([link](https://gohugo.io/content-management/formats/)).

Should ox-hugo just simply skip the Org-to-Markdown conversion and exports as Org directly?.

**Comment by kaushalmodi** [comment]
Hello, Inside entertain this idea when I was planning out how to develop ox-hugo. But then I stick with exporting to only Markdown. 

1. At the time, Hugo's Org parsing wasn't that good. 
2. Ox-hugo can be used as a one time Markdown exporting tool as well. Let's say you want move the Markdown files to a different static site generator. You can do that with minor sed search/replaces to the existing Markdown. 
3. Even now, with an improved Org parser by Hugo, I believe that Hugo is better with Markdown parsing than Org. 

Even if we export Org to Org again for Hugo, there won't be any step skipped. Hugo will now need to parser than Org file instead of the current Markdown file. 

So I don't see much value in Org->Org conversion. Right now, we have 2 flavors of the content: (i) Org, in which we love to write, and (ii) Markdown, which is the best format for Hugo to parse. :)

So there's no plan for Org->Org parsing.

**Comment by whhone** [comment]
Thanks Kaushal for the context. 

When exporting to Markdown, there are 3 formats (Org, Markdown, HTML) in total.
When exporting to Org, there are 2 formats (Org, HTML) in total.
In my opinion, with less format involved, it is less likely to have compatibility issue. (but this might not really a problem in reality)

**Comment by kaushalmodi** [comment]
When using ox-hugo, you should need to only worry about the initial Org source.  Think of the Markdown created by ox-hugo and the HTML created by Hugo as part of a "compilation" process. 

Moreso, you can even automate the ox-hugo export + Hugo run flow. So the intermediate format between ox-hugo and Hugo. So I don't see a value in supporting Org as an intermediate format -- that intermediate file will always anyways be auto generated. 

The choice to keep Markdown as the intermediate format is because that's the best one support by Hugo. Few months back, that even got better when Hugo's default Markdown switched from the BlackFriday Markdown to CommonMark.

As I am trying to keep the ox-hugo project as robust as possible (always trying to add a new test to its test suite), I don't see a value-add by adding Org as an intermediate format for Hugo consumption.

**Comment by whhone** [comment]
I am just sharing my thoughts and you can make the final call and I think this is a minor thing.

**Comment by kaushalmodi** [comment]
@whhone I really appreciate that you brought up this question for discussion. For this topic though, my final call is to support only Markdown export. You are always welcome to bring up questions and especially bug reports if you find any issue with ox-hugo :)
