### ISSUE TITLE
Auto export on save not working

### ISSUE THREAD

**Issue by dpineiden** [kaushalmodi/ox-hugo#427]
Hi.

My emacs version is 26.1 with spacemacs.

I created the file and added the configuration on the same folder where I save the org files, close an open again, trying to reload and nothing.

It's not clear how update or bind the file with the project. What can I do?

Thanks!

**Comment by kaushalmodi** [comment]
Hello, the instructions on https://ox-hugo.scripter.co/doc/auto-export-on-saving/ should work regardless of the Emacs config you use because the auto-export feature works using the basic Emacs feature (I think these features are at least a decade old) of File Local Variables or `.dir-locals.el`.

I am unable to help as I don't have enough information to reproduce the issue you are seeing.
