### ISSUE TITLE
Is there a Hugo theme that works best with ox-hugo?

### ISSUE THREAD

**Issue by pmeckoni** [kaushalmodi/ox-hugo#432]
This is more of a support request than an issue.

I understand there are some small tweaks required by ox-hugo for better Hugo performance. I found two for now:
1. https://ox-hugo.scripter.co/doc/org-toc/#excluding-org-generated-toc-from-hugo-summaries
2. https://ox-hugo.scripter.co/doc/equations/#fn:1

Is there any theme that works perfectly with ox-hugo so I don't have to spend time on checking / fixing the theme?

I could [not get w3c validation](https://validator.w3.org/nu/?doc=https%3A%2F%2Fpeople.umass.edu%2Fmeckoni%2Farticles%2Fworking_offline%2F) with my modified hugo-xmin because of the ox-hugo toc style tag. So I'm looking for recommendations.

**Comment by kaushalmodi** [comment]
Hello,

>Is there any theme that works perfectly with ox-hugo so I don't have to spend time on checking / fixing the theme?

You should find many themes that people use with `ox-hugo` + Hugo on the [Real World Examples](https://ox-hugo.scripter.co/doc/examples/) page. I am unable to do any qualitative analysis of those, but you can browse through the example and see which one works the best for you. 

Regarding that specific w3c validation error, it's because ox-hugo needs to use a hard-coded style tag to suppress showing bullets if you choose to export with section numbers enabled. If you export without section numbers, that style tag won't be added.

Ref: https://github.com/kaushalmodi/ox-hugo/blob/be89fea0bf6b89143d4b98ae86dee9eb822759bb/ox-hugo.el#L1106-L1114

**Comment by pmeckoni** [comment]
Thanks.
