### ISSUE TITLE
Derive EXPORT_FILE_NAME, from slug and date?

### ISSUE THREAD

**Issue by angerman** [kaushalmodi/ox-hugo#435]
Apologies if this has been asked before and I've simply not found the item. I've imported a lot of posts from a previous blog, after running it through pandoc and some post processing. Now I'm left with a massive org document, that has titles, and dates, and ... well lots of duplicate EXPORT_FILE_NAMEs. What happened is that I did a monthly update with the same title. Thus the slug resulted in the same string. After migrating this I've got a bunch of subtrees all with the same value for the EXPORT_FILE_NAME property. I've also seen that hugo puts the filenames as the url by default. So I'm wondering if it would make sense to derive the EXPORT_FILE_NAME from the title + the date?

I guess I could write a function that walks over the org tree, and sets the EXPORT_FILE_NAME to the concatenation of the <date>-<slug>.

I'm just left a bit confused, think I'm holding this wrong, as I can't be the first one to run into this issue?  While I understand that this might be something rather specific for a blog like setup, maybe there is in general some use for a export_file_name hook?

**Comment by angerman** [comment]
Eventually I came up with something like this, in case someone else is looking for a solution:
```elisp
(defun ox-date-slug-prop ()
  (interactive)
  (let ((dt (format-time-string "%Y-%m-%d" (apply #'encode-time (org-parse-time-string (org-entry-get (point) "EXPORT_DATE")))))
        (slug (org-hugo-slug (org-get-heading :no-tags :no-todo))))
    (org-set-property "EXPORT_FILE_NAME" (format "%s-%s" dt slug))))
```

bound to a key, and called on each subtree does the trick. It's not that pretty but works. I'd like a slightly more automated solution, but this is as good as it gets right now.

**Comment by kaushalmodi** [comment]
Hello,

I am glad you figured this out on your own. I was going to suggest doing the same.

Here are some earlier related discussions:
- https://github.com/kaushalmodi/ox-hugo/issues/32#issuecomment-330518161
- https://github.com/kaushalmodi/ox-hugo/issues/88#issue-268978412

---

Setting the `EXPORT_FILE_NAME` is out of the scope of the `ox-hugo` package because this package is designed to _consume_ the value the user sets for that property, not auto-set it. In-fact, the exporter is **not** supported to set or edit anything in the Org file it is exporting.

Reasoning:
- Prevent feature creep
- Prevent the `ox-hugo` package from messing up the user's Org source in any way -- The exporter strictly updates/edits only the exported Markdown files.

That said, I have documented the use of Org Capture to pre-determine the values of `EXPORT_FILE_NAME` (and any other Org drawer property you like) [here](https://ox-hugo.scripter.co/doc/org-capture-setup/). See if that suits your flow. 

From what I understand, you would need to manually run your snippet only 1 time, when you are converting your existing posts to the `ox-hugo` flow, right? Going forward, Org Capture might help you uniquify the `EXPORT_FILE_NAME` if you still would like to prefix date to the exported file name.

---

This is Hugo, so there are many ways to do the same thing...
- May be have sections like look like _/yyyy/mm/dd/mypost.md_ ?

**Comment by kaushalmodi** [comment]
I'll close this issue as it's out of the `ox-hugo` scope, but we can continue having discussion in this thread.
