### ISSUE TITLE
When exporting ox-hugo to markdown, the line ends with Chinese symbols or Chinese characters, but does not wrap. How can I solve this problem?

### ISSUE THREAD

**Issue by iT-Boyer** [kaushalmodi/ox-hugo#451]
## How to Reproduce the Issue
When exporting ox Hugo to MD, the line ends with Chinese symbols or Chinese characters, but does not wrap.
### Example Org File
Example.org
```org
* Example
同文输入法。
使用输入法配置库：rimerc, 大牛配置好的配置，包括同文和squirrel 配置。
配置路径在`/sdcard/rime`, 将`rimerc` 库中的trime.z7 解压到该目录。

```
### Generated Markdown File or Error
Example.md
```md
# Example
同文输入法。使用输入法配置库：rimerc, 大牛配置好的配置，包括同文和squirrel 配置。配置路径在`/sdcard/rime`, 将`rimerc` 库中的trime.z7 解压到该目录。
```

**Comment by kaushalmodi** [comment]
Hello,

The unwrapping was done intentional as a result of this issue: https://emacs-china.org/t/ox-hugo-auto-fill-mode-markdown/9547/5

The code responsible for this behavior is here:

https://github.com/kaushalmodi/ox-hugo/blob/8345ceb90ff1314d598c6b67ba6ee7616e2b0bc4/ox-hugo.el#L2548-L2556

I do not read or write Mandarin. So a PR to improve this behavior is welcome. You may even ping the original posters on that emacs-china.org thread to get ideas on how to improve this behavior.

**Comment by kaushalmodi** [comment]
Closing this issue for now. 

I can reopen this once I have more info.
