### ISSUE TITLE
It's time to release a new version

### ISSUE THREAD

**Issue by tianheg** [kaushalmodi/ox-hugo#563]
Hello, thanks for your wonderful work and others'.

I want to enable `org-hugo-auto-export-mode`, however it isn't included with the v0.8(the latest version on MELPA stable).

Later I found that I can install from MELPA

**Comment by kaushalmodi** [comment]
Hello, the burden of writing the long changelog is preventing me from making another release. 

Also, I recommend only using Melpa (not Melpa Stable) for ox-hugo. 

I'll see if I can do this in the coming weeks.

**Comment by tianheg** [comment]
Thanks!

Searching way to install ox-hugo from Melpa (not Melpa Stable)

**Comment by kaushalmodi** [comment]
I'll leave this open as a CHANGELOG doc issue. Yes, but please switch to Melpa for updating this package.

**Comment by kaushalmodi** [comment]
Here's one of the SO answers on how you can specify which archive to install a package from: https://stackoverflow.com/a/38648126/1219634

**Comment by tianheg** [comment]
Thanks for your help, I installed ox-hugo successfully

**Comment by tianheg** [comment]
Now I can use `org-hugo-auto-export-mode`, I'm very happy 😄

**Comment by maddovr** [comment]
My 2¢ on this: 
Not many people really want to use melpa (or package.el for that matter). I for example use guix as the emacs package manager (since I also use Guix System), and in guix repo (channel) emacs-ox-hugo is at version 0.8. I use my own channel and have been updating ox-hugo every couple of months, but guix tries to follow melpa stable for emacs-packages. A stable release would be great. I've skimmed the commit history a bit and perhaps it might be worth to skip the changelog for the minor fixes and only mention the breaking/huge changes. Writing the changelog at a later time might also be preferrable. I'll see if I can scrunch up some time next weekend to help if things aren't moving by then but I make no promises.

**Comment by kaushalmodi** [comment]
> I'll see if I can scrunch up some time next weekend to help if things aren't moving by then but I make no promises.

Thank you! btw I plan to go inactive for the next month or so as I will be on vacation and then on work catchup. If you have time, I'll appreciate a CHANGELOG PR.

Once we have a baseline CHANGELOG file, it will be easy to keep it updated with each new bugfix or feature addition.

**Comment by kaushalmodi** [comment]
I am also open to an automated CHANGELOG generation (from git commit messages) that updates the CHANGELOG.org file using a `make` target.

**Comment by kaushalmodi** [comment]
@tianheg I have tagged a new release v0.9.0.

@maddovr I went the route of auto-generating the CHANGELOG using https://github.com/orhun/git-cliff.

The changelog for v0.9.0 is at https://ox-hugo.scripter.co/doc/changelog/#0-dot-9-dot-0.
