### ISSUE TITLE
How to clever reference in ox-hugo [feature question]?

### ISSUE THREAD

**Issue by RidaAyed** [kaushalmodi/ox-hugo#600]
Given the snippet below, is clever referencing in ox-hugo possible i.e. `Cref:fig:foo` would be html rendered to `Figure foo`. In other words: Does - for us already spoiled ox-hugo users - a ox-hugo equivalent of the Tex [cleveref](https://www.ctan.org/tex-archive/macros/latex/contrib/cleveref?lang=en) package exist? 

```org
#+CAPTION: lorem
#+NAME: fig:foo
[[foo.jpg]]
```

**Comment by kaushalmodi** [comment]
If you do `[[fig:foo]]`, it should be rendering to "Figure \<number\>" already. It won't do "Figure foo".

**Comment by kaushalmodi** [comment]
If you do `[[fig:foo]]`, it renders to "\<number\>". I can easily add the "Figure " prefix before it, but that would be a breaking change for people already using `[[fig:foo]]` type of links. 

I'll need to think about this.

**Comment by kaushalmodi** [comment]
@RidaAyed I think what you want should be possible using `org-link-set-parameters` where you define custom links "cref" and "Cref". 

See https://orgmode.org/manual/Adding-Hyperlink-Types.html.

Do you want to try out that approach and get back? I cannot add the special cref and other special links within ox-hugo, because if the user exports an Org document with these special links in other formats (ox-html, etc.) they will get broken link errors. 

Instead if you define these custom types yourself, the exports will work in all the formats you define in org-link-set-parameters. 

While I cannot integrate that in ox-hugo, and can mention how to do this customization if you get back after your research on this with a solution that works for you.

**Comment by kaushalmodi** [comment]
You'll find a lot more examples on this blog post by @jkitchin: https://kitchingroup.cheme.cmu.edu/blog/2016/11/04/New-link-features-in-org-9/

**Comment by RidaAyed** [comment]
My recent encounter of John Kitchin's org-ref brought up that question let alone the awareness of clever ref. I'll look into your proposal and how to apply it to my org-ref oriented file (cref only, no square brackets at all). Once again thank you for your lightning fast reaction.

**Comment by kaushalmodi** [comment]
@RidaAyed I just documented this [link desc auto-prefixing feature](https://ox-hugo.scripter.co/doc/linking-numbered-elements/#auto-prefixing-element-type-names-in-links) that `ox-hugo` has had for a while. See if that helps.

This doesn't support the `cref` vs `Cref` kind of functionality though. The figure links will always have the "Figure" prefix.

Here's a related test (it's a test for element type names in German though): https://ox-hugo.scripter.co/test/singles/links-to-org-elements/#links-to-images

**Comment by kaushalmodi** [comment]
@RidaAyed Let me know if the [above comment](https://github.com/kaushalmodi/ox-hugo/issues/600#issuecomment-1073078730) helps, or if you need a case-sensitive feature like cref vs Cref. 

If you need cref vs Cref, that will be out of the scope of ox-hugo, but should be possible using `org-link-set-parameters`.

**Comment by kaushalmodi** [comment]
Hello, I'll close this issue for now. Feel free to comment here further.
