### ISSUE TITLE
Support #+attr_shortcode for unpaired shortcodes 

### ISSUE THREAD

**Issue by muihlinn** [kaushalmodi/ox-hugo#624]
I need to use a unpaired shortcode which uses a long list of attributes.

I tried this in a subtree:

```
#+attr_shortcode: :position horizontal
#+attr_shortcode: :path static/img/legacy/works/land
#+ hugo: {{<album>}}
```
but that generates just an `{{<album>}}` shortcode in the .md file whitout any argument.

I've made it work faking a paired shortcode  using this code

```
#+attr_shortcode: :position horizontal
#+attr_shortcode: :path static/img/legacy/works/land
#+begin_album
ignore this
#+end_album
```
and placing .Inner into a  unused template variable

The shortcode argument list is longer than showed here for clarity.

**Comment by kaushalmodi** [comment]
`#+attr_shortcode` won't work with unpaired shortcode. 

Can you give an example of how you want that shortcode, with its attributes to look like in the exported Markdown?

**Comment by muihlinn** [comment]
Sorry, I managed to send the issue before typing any content. :-/
Now that I have a workaround, it'll be nice to have a consistent markup in org for all the shortcodes. Most unpaired do not have any arguments, or could be typed inline, but I have a couple which really needs them.

**Comment by kaushalmodi** [comment]
Related: Check out how you can use Org macros to mask Hugo shortcodes: https://ox-hugo.scripter.co/doc/shortcodes/#org-macros.

**Comment by muihlinn** [comment]
> But if any of the above 2 methods I mentioned don't work, it's a bug, and I'll look into fixing them.

those worked fine for other shortcodes. Thanks.

I have the code going on, it's an old site backport. Tons of legacy stuff to be converted. It'll be messy anyway, so don't worry much :)

**Comment by kaushalmodi** [comment]
> those worked fine for other shortcodes

So it doesn't work just for that `album` shortcode? 😕 

If you can paste a snippet of the expected Markdown containing that shortcode, I can add it to the test suite. 

(Also make sure you are using the latest version of ox-hugo.)

**Comment by kaushalmodi** [comment]
@muihlinn I am unable to reproduce the issue you are seeing with `#+hugo:`. In any case, I have added a test showing how to use `#+hugo` with unpaired shortcode requiring attributes in https://github.com/kaushalmodi/ox-hugo/commit/2b762139bc8e68b97ef17420cec2df1fcec1ef13.

**Comment by muihlinn** [comment]
I'm afraid I've failed to express the issue, which is more a feature request than a bug.

## org code
```org
** entry
:PROPERTIES:
:EXPORT_FILE_NAME: entry
:EXPORT_DATE: 2022-04-23T08:28:28
:END:

#+hugo: {{< me >}}

#+attr_shortcode: :files /static/img/legacy/works/2004v
#+hugo: {{< album >}}
```
## markdown generated, as expected

```markdown
+++
title = "entry"
author = ["Luis Miguel Castañeda"]
date = 2022-04-23T08:28:28
lastmod = 2022-04-23T08:29:07+02:00
draft = false
+++

{{< me >}}

{{<album>}}
```
# what I would like to be generated

```markdown
{{<album files="/static/img/legacy/works/2004v">}}
```
# why?

For this project, album, and a few others shortcodes have a fairly long list of arguments which I've simplified for the example. A couple of folders to look in and a few configuration options, I'tll be more readable/consistent if something with this kind of notation would work straight away.

Let's say:

```org
#+attr_shortcode: :files /static/img/legacy/works/2004v
# any number of attributes here
#+shortcode: album 
```
would generate 

```markdown
{{<album files="/static/img/legacy/works/2004v"  >}}
```
with the argument list previously stated as `#+begin_album`  will do.

I understand that's a special case which doesn't fit well in most tools (macros, etc), nor in the ox-hugo orientation as you said previously, but well, to me at least makes sense.

**Comment by kaushalmodi** [comment]
Thanks for explaining. So you basically want to specify each attribute, one per line, for readability. And if you attempt the `#+hugo` style, that works but is not readable as it creates a long line with all the attributes. 

---

> ```
> #+attr_shortcode: :files /static/img/legacy/works/2004v
> #+hugo: {{< album >}}
> ```

This is difficult to support because syntactically, `#+hugo:` can have any string after it. It could be `#+hugo: foo bar zoo`. In that case, is would be tricky on how to match the attributes with what. 

---

> ```
> #+attr_shortcode: :files /static/img/legacy/works/2004v
> # any number of attributes here
> #+shortcode: album 
> ```

This is a better suggestion. But because it's mainly for a style change, I'd like to skip implementing this one in ox-hugo.

---

### Suggestion

You can create your custom shortcodes that redefines the original album shortcode to make it more concise.

Ideas:

- It accepts shorter notations like "h" for horizontal
- If you tend to use the same "horizontal" parameter always, may be you make that the default inside the shortcode definition so that you don't have specify it. 
- The paths are getting too long. May be you specify the common path prefix used in the whole post as front matter. The shortcode then prefixes that front matter param if present. That way your paths will get shorter.

If above works out for you, you can have the shortcode look like:

```
#+hugo: {{< album path="foo" >}}
```

**Comment by kaushalmodi** [comment]
@muihlinn Alternatively, multi-line shortcodes work too!

Try something like this:

```
#+begin_export hugo
{{< album
      position="horizontal"
      path="static/img/legacy/works/land" 
>}}
#+end_export
```

**Comment by muihlinn** [comment]
Please add this to the documentation. I had a huge deal of of inlined shortcodes in my org files which stopped working and this would have saved up a considerable amount of time in its conversion.

**Comment by kaushalmodi** [comment]
The `#+begin_export hugo` is documented at https://ox-hugo.scripter.co/doc/shortcodes/#plus-begin-export-hugo.

That block can literally contain anything you would type otherwise in the Markdown content files. It's not specific to multi-line shortcodes. But because Hugo supports multi-line shortcodes, you can use those in those _export_ blocks as well. 

I'll add this second example of using multi-line shortcode in that section as well.

**Comment by kaushalmodi** [comment]
Added https://ox-hugo.scripter.co/doc/shortcodes/#multi-line-shortcodes.
