### ISSUE TITLE
Merge ox-blackfriday and ox-hugo?

### ISSUE THREAD

**Issue by kaushalmodi** [kaushalmodi/ox-hugo#65]
Hello @titaniumbones :

What do you think about merging `ox-blackfriday` and `ox-hugo`? I believe Blackfriday (being a Go package) is primarily used by Hugo. So I don't see much re-use of Blackfriday.

Additionally, keeping `ox-blackfriday` separate adds some clutter to the \*Org Export Dispatcher\* menu, which I believe, will go unused:

![image](https://user-images.githubusercontent.com/3578197/29750660-aed67a98-8b11-11e7-8284-b7ea999eb9cf.png)

That also occupies the `b` binding.

If there is no objection, I can go ahead and merge `ox-blackfriday` into `ox-hugo`.

This is in efforts to finally release `ox-hugo` as a package, probably on both GNU Elpa and MELPA.

**Comment by titaniumbones** [comment]
I'm really sorry for the delay -- I thought I'd responded to this a couple of days ago.

- I see your point about the clutter!
- I guess this would be fine, but I think in the long term we (orgers) should be thinking more seriously about markdown flavour support. Blackfriday will be used for more and more projects as Go expands, I think. And in general we will eventually want a better way of handling the many md flavours...
- would you maybe be able to keep the code namespaced to blackfriday & spatially segregated in ox-hugo.el so that it could be re-extracted at a future date if need be?

**Comment by kaushalmodi** [comment]
This middle ground should work for now: https://github.com/kaushalmodi/ox-hugo/commit/b807ac14aac7d63addcc3d110daed0130315587a
