### ISSUE TITLE
How to keep origin math equations? Is there is a toggle for it?

### ISSUE THREAD

**Issue by young40** [kaushalmodi/ox-hugo#653]
There are some site support `$$` better than `\[` . 

So in that case, keep the origin math equations means a lot.

Thanks!

**Comment by kaushalmodi** [comment]
> There are some site support $$ better than \[ .

I didn't quite get that. Can you provide a minimal reproducible example?

> So in that case, keep the origin math equations means a lot.

Until Hugo is able to parse the equations natively, I don't think we can remove the escaping. 

It's difficult to act upon this suggestion, unless you can share an example git repository that shows the unescaped Math equations in Markdown content work well with just Hugo + MathJax.

**Comment by young40** [comment]
@kaushalmodi thank u, got it.

I'll add a post process after exported to markdown in my work flow.

**Comment by kaushalmodi** [comment]
I haven't been able to understand your issue entirely. If you don't want `ox-hugo` to do any escaping of Math equations when exporting, you can add this Emacs-Lisp advice to your Emacs config:

```el
(defun my/org-blackfriday-escape-chars-in-equation (str)
  str)
(advice-add 'org-blackfriday-escape-chars-in-equation :override #'my/org-blackfriday-escape-chars-in-equation)
```

Sorry, I am unable to help much without a reproducible example to see the exact issue you are facing.

**Comment by 0xsvenka** [comment]
I've ran into the same issue. My workflow is to use KaTeX for math rendering at build time (as per [Hugo docs](https://gohugo.io/functions/transform/tomath/)). In this scenario, only `\(` and `\[` in Markdown files are recognized, but not `\\(` or `\\[`, which is why escaping becomes undesirable.

Anyway, the Emacs Lisp snippet provided by @kaushalmodi solves the problem nicely.
