### ISSUE TITLE
Fix attachment rewrite

### ISSUE THREAD

**Issue by kaushalmodi** [kaushalmodi/ox-hugo#69]
Hi @titaniumbones ,

Can you please try out this branch: https://github.com/kaushalmodi/ox-hugo/tree/copy-files-to-static-images-only-when-needed

From the commit message in there:

```
Earlier, the images/ directory was given too much prominence. A user
could have multiple dirs inside their static/ dir.. but the rewrite
would always happen to just static/<HUGO_STATIC_IMAGE>. That did not
look right.

Now ox-hugo tries to be smarted in figuring out where to copy the
outside-Hugo-static-dir files to.
```

I believe this will work for your flow too.. you will simply need to ensure that your outside Hugo dir structure includes **/static/**  followed by the path that you would like to see post-attachment-rewrote inside Hugo Static dir.

Here is the new behavior summary copied from **example-site/content-org/all-posts.org**:

```
If you link to files outside of the Hugo =static= directory, ensure
that the path contains =/static/= if you would like to preserve the
directory structure.

Example translations between outside =static= directory paths to the
copied location inside =static=:
|----------------------------------+-------------------------------------------+----------------------------------------------------------------------------------------------------------------------|
| Outside =static=                 | Copied-to location inside =static=        | Explanation                                                                                                          |
|----------------------------------+-------------------------------------------+----------------------------------------------------------------------------------------------------------------------|
| =~/temp/static/images/foo.png=   | =<HUGO_BASE_DIR>/static/images/foo.png=   | If the *outside* path has =/static/= in it, the directory structure after that is preserved when copied.             |
| =~/temp/static/img/foo.png=      | =<HUGO_BASE_DIR>/static/img/foo.png=      | (same as above)                                                                                                      |
| =~/temp/static/foo.png=          | =<HUGO_BASE_DIR>/static/foo.png=          | (same as above)                                                                                                      |
| =~/temp/static/articles/zoo.pdf= | =<HUGO_BASE_DIR>/static/articles/zoo.pdf= | (same as above)                                                                                                      |
| =~/temp/bar/baz/foo.png=         | =<HUGO_BASE_DIR>/static/foo.png=          | Here, as the *outside* path does not have =/static/=, the file is copied directly into the Hugo =static/= directory. |
|----------------------------------+-------------------------------------------+----------------------------------------------------------------------------------------------------------------------|
```

Note the updated location for this example too: https://github.com/kaushalmodi/ox-hugo/blob/copy-files-to-static-images-only-when-needed/example-site/files-to-be-copied-to-static/static/images/copy-of-unicorn-logo.png

Please let me know if this update works alright for you at the soonest. I will merge it in after that.

**Comment by titaniumbones** [comment]
Haven't had a chance to try it out yet but the commit looks great.  It's a far superior mechanism. Will try to play with it soon but feel free to merge before and we an fix bugs later if they emerge.

a little occupied right now trying to figure out how best to get my `reveal.js` lecture slides into the hugo-based website.  I'll want to use this code actually!

**Comment by kaushalmodi** [comment]
> Will try to play with it soon but feel free to merge before and we an fix bugs later if they emerge.

Thanks. I have merged it, with documentation added to https://github.com/kaushalmodi/ox-hugo/wiki/Image-Links

> a little occupied right now trying to figure out how best to get my reveal.js lecture slides into the hugo-based website

I might also have to tackle that soon. Let me know what you come up with

**Comment by kaushalmodi** [comment]
Fixed in https://github.com/kaushalmodi/ox-hugo/commit/1a2b8d9be4c4ccf8fddcff4561221603230e65b1

**Comment by titaniumbones** [comment]
>    a little occupied right now trying to figure out how best to get my reveal.js lecture slides into the hugo-based website

> >I might also have to tackle that soon. Let me know what you come up with

I'm thinking that the easiest way to do this is to reuse the org-hugo image rewriting code (maybe extract it into its own defun now that it's getting richer), then write a simple derived backend on top of ox-reveal.  

Unfortunately, reveal slideshows need to be run in an iframe rather than a div. so... Idon't think my first ide will work -- which was to strip out the header & footer info from the html export, and just incorporate those into the hugo templates.

So, instead, I am thinking I will export the slideshows to `static/slides/` and write a"slides" page that lists the content of that directory in a sidebar menu (using hugo's `readDir`) and opens the full reveal slideshow in an iframe in the main portion of the page.

It feels clunky. Do you have any better ideas?
I *think* one could just cut out hte preamble, nad write a hugo

**Comment by kaushalmodi** [comment]
Have you looked at this? https://github.com/minoritea/hugo-revealjs-generator

Just that applying that layout specific to a section like *slides* in a way that it blends with the rest of the site might be challenging.

**Comment by kaushalmodi** [comment]
Another example:

- http://aphecetche.github.io/#talks
- https://github.com/aphecetche/site/blob/master/layouts/talk/single.html
- https://discourse.gohugo.io/t/rawcontent-and-shortcodes/6461/5?u=kaushalmodi

**Comment by titaniumbones** [comment]
I looked at hugo-revealjs-generator -- that workflow & the one-page-per-slide setup don't seem to match my habits very well. 

The aphecetche site is interesting. Two thoughts from me about htis approach:

-  I haven't used the built-in markdown feature of revealjs. [The README says](https://github.com/hakimel/reveal.js#markdown) reveal uses github-flavoured markdown, which means it won't support class attributes. For me that would likely break a lot of my existing presentations, which often break the slides up horizontally, so I use a class to keep the slides within the grid. I currently use most of the features of ox-reveal, and I personally would want to retain those features if possible.
-  in [Abcecetche](http://aphecetche.github.io/#talks)'s setup,, clicking on a talk takes you outside of the menu system, so that you almost feel like you're not in the website anymore. That makes sense in some ways, but I think it would be disorienting for my students, and also it would make it a little hard to navigate between the lectures.  So I would like to keep the talks inside an iframe (here's an example of one current site: http://wildwater.hackinghistory.ca/article/wildwater-1-syllabus/ , which has menu apparatus on the side 7 title on the top). 

Still, the markdown export is appealling, and I prefer keeping an md file in my site repo to writing out the full html and saving that...

**Comment by titaniumbones** [comment]
Coming back to the actual topic of this issue: at present, linked images & files that are not kept in a directory tree containing a "static" dir are dumped to the root `hugo-base-dir/static` directory. This is probably a bad place for them. Can we instead keep them either in `static/images` or a new dir, say `static/ox-hugo` or similar?

**Comment by kaushalmodi** [comment]
> say `static/ox-hugo`

How about `static/misc`? I'll make the change now.. and then maybe add a defcustom if needed.

BTW is using `static/` in the source directory path impractical?

**Comment by titaniumbones** [comment]
> BTW is using static/ in the source directory path impractical?
I will do so going forward, but at present I have something like 100 lectures and I would guess around 1000 images, spread over a number of courses. I guess I could write a script to move all the images and change al lll the links, but it feels a little hard to do right now.

**Comment by kaushalmodi** [comment]
Try https://github.com/kaushalmodi/ox-hugo/commit/4620759e27858c160de60e1082d8bb28fb685e14

**Comment by titaniumbones** [comment]
btw, I was able to implement a hugo-compatible reveal export. I put it here: https://github.com/titaniumbones/ox-huveal -- it's mostly frankencode from your repo and https://github.com/yjwen/org-reveal/.  You can see the slides produced [here](http://2017.hackinghistory.ca/slides/) or [here](http://2017.hackinghistory.ca/slides/01-intro/#).  I'm using [this theme](https://github.com/titaniumbones/hugo-courses-theme/), and the menu code is [here](https://github.com/titaniumbones/hugo-courses-theme/blob/641f10c6ef6150ace684b27ac34cbe9c0dc6286b/layouts/partials/menu.html#L54-L65).

**Comment by kaushalmodi** [comment]
Try out the attachment rewrite change.. If it works for you, I'll bump the revision number.

**Comment by kaushalmodi** [comment]
Feel free to re-open this if this doesn't work for you.
