### ISSUE TITLE
Support for preserving the "results" section from code execution

### ISSUE THREAD

**Issue by jaju** [kaushalmodi/ox-hugo#77]
[Enhancement request]
Would it be possible to preserve the results from the execution of the source-blocks? (Ref: http://orgmode.org/manual/Results-of-evaluation.html#Results-of-evaluation).
goorgeous preserves it, but ox-hugo drops the results block from the generated markdown.

I wish I could figure out how to add, but honestly could not figure out how to start.

Thanks!

**Comment by kaushalmodi** [comment]
Can you share a minimum working example of the Org file to reproduce the issue you are seeing? And also the Markdown file you get as a result?

In addition, see this: https://ox-hugo.netlify.com/doc/debug/

I am a bit surprised by this report because I heavily make use of the `#+RESULTS` block in one of my posts..

- Org: https://gitlab.com/kaushalmodi/kaushalmodi.gitlab.io/raw/master/content-org/notes/string-fns-nim-vs-python.org
- `ox-hugo` generated Markdown: https://gitlab.com/kaushalmodi/kaushalmodi.gitlab.io/raw/master/content/notes/string-fns-nim-vs-python.md
- Hugo output: https://scripter.co/notes/string-functions-nim-vs-python/

**Comment by jaju** [comment]
Oh, I see that your markdown does have the results block.
Please allow me some time to create a self-contained, clean sample. It'll also allow me to check in a clean setup. I'll report the outcome here as soon as I am done. (Sorry, away from the computer for some time, but appreciate your quick and helpful response!)

**Comment by kaushalmodi** [comment]
I'd encourage to simply clone this repo and run `make test`. 

That will do the exports from the `test/site` (test Hugo site) in emacs batch mode without using your Emacs config. 

Add your example to the `test/site/content-org/all-posts.org` and run `make test` to check if you still see the issue. Report back after that.

**Comment by jaju** [comment]
Thanks. It works fine without my emacs config, and the problem appears to be due to multiple conflicting org-mode code. I'll need to take care of that.

**Comment by kaushalmodi** [comment]
Thanks for testing.

Just so that you know, shadowed load-path doesn't necessarily mean mixed Org installation.. just that you need to review if the intended Org version is shadowing the unintended Org version paths.

I had written a post that helps eradicate the unintended paths completely from the `load-path`: https://scripter.co/building-org-development-version/

See if that helps.

I use the same trick in `make test`: https://github.com/kaushalmodi/ox-hugo/blob/master/test/setup-ox-hugo.el

**Comment by jaju** [comment]
Thanks for the explanation!
Although I won't claim to understand very well, I do have two installs. One in my emacs installation, and one that is brought in by [prelude](https://github.com/bbatsov/prelude). But my usual use-cases work fine.
I'm not a regular user of Emacs - but use org-mode for my agenda/calendar and for any notes that I write.

Again, with the caveat that I don't understand this completely, I got around to getting it to work for me by adding this to my org-file (for one specific language)

#+PROPERTY: header-args:clojure :exports source :results output
I also figured out that if I had multiple language source blocks, I need to add another of the above.

I'm not sure if that's the intended manner in which this scenario should work, but it does help my case. Still to figure out more details, but as long as I'm not stuck, I get to go back to my primary work! :)

Thanks for the nice plugin!

**Comment by kaushalmodi** [comment]
> Thanks for the explanation!

Thanks. BTW I just noticed your *PS* on time stamps.. I was actually fixing that in the past week .. Now the tests run in Universal Time regardless of the actual geographical location.

> #+PROPERTY: header-args:clojure :exports source :results output
> I also figured out that if I had multiple language source blocks, I need to add another of the above.

Depending on the language and the Org Babel library, it would vary what you want to like in the RESULTS block. In most cases, setting `:results output` makes sense.

> Thanks for the nice plugin!

Thanks again :)

> PS: The tests errored at one point where the expected and actual timestamps did not match because the timezones were different. But they are a very nice addition! So, I didn't manage to try adding more of my tests with my specific org-text, as I was somewhat stuck trying to get those to pass (setting the TZ env-var to a different value etc., without modifying the test-code.) 

Please try again by updating to the master, should pass.

> But the test-code is useful to go through to learn a few things.

I plan on adding more tests as folks try out this package and present different usage scenarios that I hadn't considered.
