### ISSUE TITLE
Deep nesting subtree posts

### ISSUE THREAD

**Issue by EnigmaCurry** [kaushalmodi/ox-hugo#81]
I'd like to be able to write a book for the [docdock theme](http://docdock.netlify.com/content-organisation/). It says to nest content like this:

```
content
├── level-one
│   ├── level-two
│   │   ├── level-three
│   │   │   ├── level-four
│   │   │   │   ├── _index.md
│   │   │   │   ├── page-4-a.md
│   │   │   │   ├── page-4-b.md
│   │   │   │   └── page-4-c.md
```

I'm trying to do it as a one-org-subtree-per-post workflow, but none of my tests have worked out. Is it currently possible in ox-hugo?

I'm trying something like this:

```
* Books
** book1
   :PROPERTIES:
   :EXPORT_HUGO_SECTION: book1
   :EXPORT_FILE_NAME: _index
   :END:

   Book 1 index...

*** chapter 1
    :PROPERTIES:
    :EXPORT_HUGO_SECTION: book1/chapter1
    :EXPORT_FILE_NAME: _index
    :END:
    
    Introduction for chapter 1

**** sub section 1
     :PROPERTIES:
     :EXPORT_HUGO_SECTION: book1/chapter1
     :EXPORT_FILE_NAME: section1
     :END:
    
     Section 1 of chapter 1
```

which would create the following URLs:
 - /content/book1/_index.md
 - /content/book1/chapter1/_index.md
 - /content/book1/chapter1/section1.md

The problem mostly seems to stem from `EXPORT_HUGO_SECTION` not liking slash characters (it truncates it to the right most term, making everything fall into the top section directory.) Perhaps a different property name could be used instead like `EXPORT_HUGO_PATH`, which would specify a relative path underneath the content directory that would export the given subtree directly to.

Another problem it seems is that the `EXPORT_*` properties only seem to inherit from the immediate parent subsection, not from any higher ancestor subtree. Maybe this is an org thing and not an ox-hugo issue though?

Perhaps I'm doing this all sorts of wrong and I just need an example?

**Comment by kaushalmodi** [comment]
You mean like this? https://ox-hugo.netlify.com/test/book1 :) See https://github.com/kaushalmodi/ox-hugo/commit/f1466e2c7966659045799178b0621c5babec5ee8

---

**Biggest issue I see in your organization: You cannot nest subtrees with `EXPORT_FILE_NAME`.**

A valid Hugo subtree has the `EXPORT_FILE_NAME` set and no nested subtree should have that. 

> The problem mostly seems to stem from EXPORT_HUGO_SECTION not liking slash characters (it truncates it to the right most term, making everything fall into the top section directory.) 

I don't see that happening. It could seem like that's happening because you are nesting *valid Hugo post subtrees*.

> Perhaps a different property name could be used instead like EXPORT_HUGO_PATH, which would specify a relative path underneath the content directory that would export the given subtree directly to.

Probably is not needed, please see the above example.

> Another problem it seems is that the EXPORT_* properties only seem to inherit from the immediate parent subsection, not from any higher ancestor subtree. Maybe this is an org thing and not an ox-hugo issue though?

Again this seems to stem from the fact that subtrees with `EXPORT_FILE_NAME` were incorrectly nested.. Inheritance works fine otherwise. In the example posted example, you will see the `EXPORT_HUGO_SECTION` inheriting correctly.

> Perhaps I'm doing this all sorts of wrong and I just need an example?

Yep.

**Comment by EnigmaCurry** [comment]
Thank you! That example explains all my misconceptions and I tested it works great in the docdock theme :+1:
